### PR TITLE
switch to using react hooks and functional components

### LINKED ISSUE #16: Link to webmail is incorrect
The link to webmail. On https://www.redbrick.dcu.ie/Services is not correct it should be https://webmail.redbrick.dcu.ie/?/Mobile/

### PR DESCRIPTION
**Pull request by butlerx**
This Pr is rather large because react hooks a quite different but they result in far less boilerplate and more easily understood code.

As part of this PR, I also removed the style of map and push in favour of pure maps as this is far simpler and more efficient.

This PR closes #16 #14 #15 #13 #11 #9 #8 #7 #6 #5 #4 #3 and #1 
It also Makes it possible to stop using stock images ala #12 
and fixes some of the issues listed in #10

### CODE REVIEW

**Comment by theycallmemac** [comment]
@butlerx good work on this - I've requested a review from @Frazl as his input is better here than mine.

File: src/Components/committee.js [hunk 1]
```diff
@@ -1,38 +0,0 @@
...
-        })
-        return members
-    }
-
-
-  return (
-    <div className="Main">
-        <div className="Page-Section">
-            <h1>Please be nice to...</h1>
-            <h2>The committee for the {this.props.year} Year!</h2>
```
Comment (Frazl) [inline src/Components/committee.js]: The committee page seems to be broken since it still expects a year from props which is now undefined.

File: src/components/home.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    }
+  }
+
+  return (
+    <div className="Main">
+      <h1>Welcome</h1>
+      <h2>
+        {isEventsPage ? 'View our latest events here!' : "We are DCU's Computer Networking Society"}
+      </h2>
+      <ImageGrid images={images} />
```
Comment (Frazl) [inline src/components/home.js]: This needs to be changed to check if images have been passed. Gives an error currently on /events.

Comment (Frazl) [reply src/components/home.js]: Also appears as if committee photos aren't loading at all?

Comment (butlerx) [reply src/components/home.js]: fixed i had moved the image check inside the component but forgot to return an empty component

Comment (butlerx) [reply src/components/home.js]: committee is working locally for me any console error?

Comment (Frazl) [reply src/components/home.js]: No errors, just not appearing with their photos, only rb logo

Comment (butlerx) [reply src/components/home.js]: I Added a fall back if photos isn't specified to fall back to brick, is it just appearing for blank profiles or all?
